server:
  port: 8082
#during数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456@Console
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 10
    maxActive: 20
    maxWait: 60000
#Dubbo服务提供者配置
dubbo:
  application:
    name: provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://localhost:2181
    timeout: 100000
    register: true
    check: false
  monitor:
    protocol: registry
  scan:
    base-packages: com.example.demo.service
  provider:
    retries: 1
    delay: -1
    timeout: 60000
#Mybatis config
mybatis:
  mapper-locations: classpath*:mapping/*Mapper.xml
  type-aliases-package: com.example.demo.domain










